VAGRANTFILE_API_VERSION = "2"
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box     = "openbsd55" 
  config.vm.box_url = "https://github.com/jose-lpa/veewee-openbsd/releases/download/v0.5.5/openbsd55.box"
  config.vm.synced_folder ".", "/vagrant", type: "nfs"
  # config.vm.synced_folder ".", "/vagrant", disabled: true
    
  config.vm.provider "virtualbox" do |v|
    v.customize ["modifyvm", :id, "--nicpromisc2", 'allow-all']
  end

  config.vm.define "node1" do |node|
    node.vm.network "private_network", ip: "192.168.2.10"
    node.vm.provision "shell", inline: "echo node1 >/etc/myname"
    node.vm.provision "shell", path: "node.sh"
  end
  config.vm.define "node2" do |node|
    node.vm.network "private_network", ip: "192.168.2.11"
    node.vm.provision "shell", inline: "echo node2 >/etc/myname"
    node.vm.provision "shell", path: "node.sh"
  end
  #config.vm.define "user" do |node|
  # node.vm.network "private_network", ip: "192.168.2.2", virtualbox__intnet: true
  #  node.vm.provision "shell", inline: "echo user >/etc/myname"
  #end
  # , nictype: 'Am79C973', virtualbox__intnet: true
  # node.vm.network "private_network", ip: "192.168.2.10", nicpromisc: 'allow-all', virtualbox__intnet: true
  #node.vm.network "private_network", nictype: 'Am79C973'
  # , virtualbox__intnet: true
end
