Vagrant.configure(2) do |config|
  config.vm.box = "obsd"

  config.vm.synced_folder ".", "/vagrant", type: "nfs"
  
  config.vm.define "signer1" do |node|
    node.vm.network "private_network", ip: "192.168.3.10"
    node.vm.provision "shell", inline: "echo signer1.test >/etc/myname"
    node.vm.provision "shell", path: "./common.sh"
    node.vm.provision "shell", path: "./signer.sh"
    node.vm.provider :virtualbox do |vbox|
      vbox.check_guest_additions = false
      vbox.functional_vboxsf = false
    end
  end
  
  config.vm.define "signer2" do |node|
    node.vm.network "private_network", ip: "192.168.3.11"
    node.vm.provision "shell", inline: "echo signer2.test >/etc/myname"
    node.vm.provision "shell", path: "./common.sh"
    node.vm.provision "shell", path: "./signer.sh"
    node.vm.provider :virtualbox do |vbox|
      vbox.check_guest_additions = false
      vbox.functional_vboxsf = false
    end
  end

  config.vm.define "haproxy" do |node|
    node.vm.network "private_network", ip: "192.168.3.20"
    node.vm.provision "shell", inline: "echo haproxy.test >/etc/myname"
    node.vm.provision "shell", path: "./common.sh"
    node.vm.provision "shell", path: "./haproxy.sh"
    node.vm.provider :virtualbox do |vbox|
      vbox.check_guest_additions = false
      vbox.functional_vboxsf = false
    end
  end

  config.vm.define "mailer" do |node|
    node.vm.network "private_network", ip: "192.168.3.30"
    node.vm.provision "shell", inline: "echo mailer.test >/etc/myname"
    node.vm.provision "shell", path: "./common.sh"
    node.vm.provision "shell", path: "./mailer.sh"
    node.vm.provider :virtualbox do |vbox|
      vbox.check_guest_additions = false
      vbox.functional_vboxsf = false
    end
  end

end


